titlemapping = {
    46: "Superseded: Einführung in die grammatische Beschreibung des Deutschen",
    101: "Einführung in die grammatische Beschreibung des Deutschen",
    224: "Einführung in die grammatische Beschreibung des Deutschen",
    22: "Superseded: The Alor-Pantar languages",
    157: "The Alor-Pantar languages",
    25: "Superseded: Grammatical theory",
    195: "Superseded: Grammatical theory",
    255: "Grammatical theory",
    144: "Superseded: Analyzing meaning",
    231: "Analyzing meaning",
    234: "Beiträge zur deutschen Grammatik",
    121: "Diversity in African languages",
    120: "African linguistics on the prairie",
    192: "Theory and description in African Linguistics",
    165: "The lexeme in descriptive and theoretical morphology",
    108: "Eyetracking and Applied Linguistics",
    94: "Advances in the study of Siouan languages and linguistics",
    173: "Diachrony of differential argument marking",
    181: "Quality aspects in institutional translation",
    159: "Order and structure in syntax I",
    182: "The languages of Malta",
    132: "Empirical modelling of translation and interpreting",
    151: "On looking into words (and beyond)",
    76: "New directions in corpus-based translation studies",
    81: "The future of dialects",
    160: "A aquisição de língua materna e não materna",
    107: "New perspectives on cohesion and coherence",
    287: "The verb in Nyakyusa",
    156: "Further investigations into the nature of phrasal compounding",
    115: "Order and structure in syntax II",
    184: "Multiword expressions",
    180: "Learning context effects",
    189: "Advances in formal Slavic linguistics 2016",
    152: "Unity and diversity in grammaticalization scenarios",
    96: "Dependencies in language",
    204: "Multiword expressions at length and in depth",
    201: "Perspectives on information structure in Austronesian languages",
    48: "Natural causes of language",
    17: "A grammar of Pite Saami",
    214: "Form and formalism in linguistics",
    209: "Interpreting and technology",
    89: "The empirical base of linguistics",
    106: "Language technologies for a multilingual Europe",
    235: "Arabic and contact-induced change",
    103: "Annotation, exploitation and evaluation of parallel corpora",
    190: "East Benue-Congo",
    227: "Definiteness across languages",
    237: "Grammatical gender and linguistic complexity II",
    83: "A grammar of Yauyos Quechua",
    141: "Superseded: The Verb in Nyakyusa",
    149: "Superseded: Beiträge zur deutschen Grammatik",
    226: "African linguistics across the disciplines",
    49: "The Talking Heads experiment",
    88: "Thoughts on grammaticalization",
    66: "A grammar of Yakkha",
    75: "Linguistic variation, identity construction and cognition",
    167: "On this and other worlds",
    20: "Syntax und Valenz",
    124: "A grammar of Rapa Nui",
    153: "The semantic transparency of English compound nouns",
    74: "A dictionary and grammatical outline of Chakali",
    27: "Grammaire des constructions elliptiques",
    78: "A grammar of Papuan Malay",
    98: "The Ik language",
    19: "Adjective attribution",
    73: "Grammaticalization in the North",
    191: "The numeral system of Proto-Niger-Congo",
    143: "Sémantique formelle",
    102: "Crossroads between contrastive linguistics, translation studies and machine translation",
    220: "Explanation in typology",
    18: "A typology of marked-S languages",
    52: "The evolution of case grammar",
    176: "The Unicode cookbook for linguists",
    223: "Grammatical gender and linguistic complexity I",
    91: "Roots of language",
    202: "Representation and parsing of multiword expressions",
    183: "Methods in prosody",
    82: "A grammar of Palula",
    148: "Corpus linguistics",
    67: "A grammar of Mauwake",
    259: "Head-Driven Phrase Structure Grammar",
    225: "The Mehweb language",
    215: "Agreement, case and locality in the nominal and verbal domains",
    249: "Highly complex syllable structure",
    97: "Die Sprachwissenschaft",
    275: "Syntactic architecture and its consequences I",
    53: "The evolution of grounded spatial language",
    51: "Language strategies for the domain of colour",
    16: "Prosodic detail in Neapolitan Italian",
    174: "A typology of questions in Northeast Asia and beyond",
    50: "How mobile robots can self-organise a vocabulary",
    118: "A grammar of Moloko",
    212: "A grammar of Komnzo",
    111: "Modeling  information structure in a cross-linguistic perspective",
    199: "René de Saussure and the theory of word formation",
    85: "A grammar of Pichi",
    216: "Bridging constructions",
    155: "Morphologisch komplexe Wörter",
    203: "The acrolect in Jamaica",
    254: "Agree to Agree",
    221: "Gemination and degemination in English affixation",
    175: "Distribution und Interpretation von Modalpartikel-Kombinationen",
    123: "Attributive constructions in North-Eastern Neo-Aramaic",
    109: "Tone in Yongning Na",
    193: "Deletion phenomena in comparative constructions",
    166: "Ship English",
    134: "Absolute Komplexität in der Nominalflexion",
    239: "The role of constituents in multiword expressions",
    200: "Curso de semântica formal",
    258: "Dative constructions in Romance and beyond",
    196: "Problem solving activities in post-editing  and translation from scratch",
    260: "Advances in formal Slavic linguistics 2017",
    282: "Demonstratives in discourse",
    295: "A grammar of Japhug",
    276: "Syntactic architecture and its consequences II",
    261: "Evidentiality, egophoricity and engagement",
    242: "The spell-out algorithm and lexicalization patterns",
    263: "Getting others to do things",
    137: "Tonal placement in Tashlhiyt",
    268: "Third language acquisition",
    296: "Empirical studies in translation and discourse",
    253: "Greece’s labyrinth of language",
    245: "A dictionary and grammatical sketch of Dagaare",
    187: "Can integrated titles improve the viewing experience?",
    290: "Multilingualism and third language acquisition",
    157: "The Alor-Pantar languages²",
    116: "Sprachliche Imitation",
    154: "Dynamische Modellierung von Artikulation und prosodischer Struktur",
    163: "A lexicalist account of argument structure",
    195: "Grammatical theory²",
    255: "Grammatical theory³",
    210: "Sound change, priming, salience",
    197: "Syntax with oscillators and energy levels",
    186: "Analogical classification in formal grammar",
    233: "Information-theoretic causal inference of  lexical flow",
    250: "A grammar of Sanzhi Dargwa",
    278: "Interpreting language-learning data",
    283: "Nominal anchoring",
    252: "Quantification and scales in change",
    286: "Historical journey in a linguistic archipelago",
    280: "Advances in formal Slavic linguistics 2018",
    303: "Computational approaches to semantic change",
    277: "Syntactic architecture and its consequences III",
    312: "Forthcoming: The Handbook of Lexical Functional Grammar",
    288: "Translation, interpreting, cognition",
    304: "Formulaic language",
    311: "Holisms of communication: The early history of audio-visual sequence analysis",
    313: "Individual differences in early instructed language learning",
    178: "Information structure in spoken Japanese",
    251: "Sound structure and sound change",
    219: "Information structure in Isthmus Zapotec narrative and conversation",
    179: "A tale of two dialect regions",
    305: "German(ic) in language contact",
    281: "Categoriality and continuity in prosodic prominence",
    265: "Utterance structure in initial L2 acquisition",
    80: "Dual aspectual forms and event structure in Caribbean English Creoles",
    256: "The clausal syntax of German Sign Language",
    213: "Multi-verb constructions in Eastern Indonesia",
    228: "Metathesis and unmetathesis in Amarasi",
    274: "Language and scientific explanation",
    248: "Communication and content",
    271: "Voice at the interfaces",
    230: "Die Entwicklung des Definitartikels im Althochdeutschen",
    194: "Semantic differences in translation",
    177: "语法理论",
    270: "On a law of Indo-European word order",
    299: "OV and VO variation in code-switching",
    298: "A grammar of Gyeli",
    262: "One-to-many-relations in morphology, syntax, and semantics",
    317: "Subatomic quantification",
    316: "Formal approaches to number in Slavic and beyond",
    308: "A grammar of Tuatschin",
    315: "Voice syncretism",
    150: "Russian verbal prefixation",
    142: "Reflections on language evolution",
    327: "Phonology in the Twentieth Century",
    326: "A dictionary and grammatical sketch of Ruruuli-Lunyala",
    332: "Forthcoming: Contemporary research in minority and diaspora languages of Europe",
    323: "The size of things",
    289: "Explaining Russian-German code-mixing: A usage-based approach",
    321: "Experimental investigations on the syntax and usage of fragments",
    236: "Prácticas lingüísticas heterogéneas",
    292: "Forthcoming: Language change for the worse",
    320: "Emergent phonology",
    318: "Paradigms regained",
    339: "Clitics in the wild",
    340: "Informationsintegration in mehrsprachigen Textchats",
    329: "Morphosyntactic change in Late Modern Swedish",
    341: "The emergence of American English as a discursive variety",
}
