titlemapping = {
                    46:      u"Superseded: Einführung in die grammatische Beschreibung des Deutschen",
                    101:     u"Einführung in die grammatische Beschreibung des Deutschen",
                    224: u"Einführung in die grammatische Beschreibung des Deutschen",
                    22:      u"Superseded: The Alor-Pantar languages",
                    157:     u"The Alor-Pantar languages",
                    25:      u"Superseded: Grammatical theory",
                    195:     u"Superseded: Grammatical theory",
                    255:     u"Grammatical theory",
                    144: u"Superseded: Analyzing meaning",
                    231: u"Analyzing meaning",
                    234: u"Beiträge zur deutschen Grammatik",
                    121:     u"Diversity in African languages",
                    120: u"African linguistics on the prairie",
                    192: u'Theory and description in African Linguistics',
                    165: u"The lexeme in descriptive and theoretical morphology",
                    108: u"Eyetracking and Applied Linguistics",
                    94:  u"Advances in the study of Siouan languages and linguistics",
                    173: u"Diachrony of differential argument marking",
                    181: u"Quality aspects in institutional translation",
                    159: u"Order and structure in syntax I",
                    182: u"The languages of Malta",
                    132: u"Empirical modelling of translation and interpreting",
                    151:     u"On looking into words (and beyond)",
                    76:      u"New directions in corpus-based translation studies",
                    81:      u"The future of dialects",
                    160:     u"A aquisição de língua materna e não materna",
                    107: u"New perspectives on cohesion and coherence",
                    287: u"The verb in Nyakyusa",
                    156: u"Further investigations into the nature of phrasal compounding",
                    115: u"Order and structure in syntax II",
                    184: u"Multiword expressions",
                    180: u"Learning context effects",
                    189: u"Advances in formal Slavic linguistics 2016",
                    152: u"Unity and diversity in grammaticalization scenarios",
                    96:  u"Dependencies in language",
                    204: u"Multiword expressions at length and in depth",
                    201: u"Perspectives on information structure in Austronesian languages",
                    48:  u"Natural causes of language",
                    17:  u"A grammar of Pite Saami",
                    214: u"Form and formalism in linguistics",
                    209: u"Interpreting and technology",
                    89:  u"The empirical base of linguistics",
                    106: u"Language technologies for a multilingual Europe",
                    235: u"Arabic and contact-induced change",
                    103: u"Annotation, exploitation and evaluation of parallel corpora",
                    190: u"East Benue-Congo",
                    227: u"Definiteness across languages",
                    237: u"Grammatical gender and linguistic complexity II",
                    83:  u"A grammar of Yauyos Quechua",
                    141: u"Superseded: The Verb in Nyakyusa",
                    149: u"Superseded: Beiträge zur deutschen Grammatik",
                    226: u"African linguistics across the disciplines",
                    49:  u"The Talking Heads experiment",
                    88:  u"Thoughts on grammaticalization",
                    66:  u"A grammar of Yakkha",
                    75:  u"Linguistic variation, identity construction and cognition",
                    167: u"On this and other worlds",
                    20:  u"Syntax und Valenz",
                    124: u"A grammar of Rapa Nui",
                    153: u"The semantic transparency of English compound nouns",
                    74:  u"A dictionary and grammatical outline of Chakali",
                    27:  u"Grammaire des constructions elliptiques",
                    78:  u"A grammar of Papuan Malay",
                    98:  u"The Ik language",
                    19:  u"Adjective attribution",
                    73:  u"Grammaticalization in the North",
                    191: u"The numeral system of Proto-Niger-Congo",
                    143: u"Sémantique formelle",
                    102: u"Crossroads between contrastive linguistics, translation studies and machine translation",
                    220: u'Explanation in typology',
                    18:  u"A typology of marked-S languages",
                    52:  u"The evolution of case grammar",
                    176: u"The Unicode cookbook for linguists",
                    223: u"Grammatical gender and linguistic complexity I",
                    91:  u"Roots of language",
                    202: u"Representation and parsing of multiword expressions",
                    183: u"Methods in prosody",
                    82:  u"A grammar of Palula",
                    148: u'Corpus linguistics',
                    67:  u"A grammar of Mauwake",
                    259: u"Head-Driven Phrase Structure Grammar",
                    225: u"The Mehweb language",
                    215: u"Agreement, case and locality in the nominal and verbal domains",
                    249: u"Highly complex syllable structure",
                    97:  u"Die Sprachwissenschaft",
                    275: u"Syntactic architecture and its consequences I",
                    53:  u"The evolution of grounded spatial language",
                    51:  u"Language strategies for the domain of colour",
                    16:  u"Prosodic detail in Neapolitan Italian",
                    174: u"A typology of questions in Northeast Asia and beyond",
                    50:  u"How mobile robots can self-organise a vocabulary",
                    118: u"A grammar of Moloko",
                    212: u"A grammar of Komnzo",
                    111: u"Modeling  information structure in a cross-linguistic perspective",
                    199: u"René de Saussure and the theory of word formation",
                    85:  u"A grammar of Pichi",
                    216: u"Bridging constructions",
                    155: u"Morphologisch komplexe Wörter",
                    203: u"The acrolect in Jamaica",
                    254: u"Agree to Agree",
                    221: u"Gemination and degemination in English affixation",
                    175: u"Distribution und Interpretation von Modalpartikel-Kombinationen",
                    123: u"Attributive constructions in North-Eastern Neo-Aramaic",
                    109: u"Tone in Yongning Na",
                    193: u"Deletion phenomena in comparative constructions",
                    166: u"Ship English",
                    134: u"Absolute Komplexität in der Nominalflexion",
                    239: u"The role of constituents in multiword expressions",
                    200: u'Curso de semântica formal',
                    258: u"Dative constructions in Romance and beyond",
                    196: u"Problem solving activities in post-editing  and translation from scratch",
                    260: u"Advances in formal Slavic linguistics 2017",
                    282: u"Demonstratives in discourse",
                    295: u"A grammar of Japhug",
                    276: u"Syntactic architecture and its consequences II",
                    261: u"Evidentiality, egophoricity and engagement",
                    242: u"The spell-out algorithm and lexicalization patterns",
                    263: u"Getting others to do things",
                    137: u"Tonal placement in Tashlhiyt",
                    268: u"Third language acquisition",
                    296: u"Empirical studies in translation and discourse",
                    253: u"Greece’s labyrinth of language",
                    245: u"A dictionary and grammatical sketch of Dagaare",
                    187: u"Can integrated titles improve the viewing experience?",
                    290: u"Multilingualism and third language acquisition",
                    157: u"The Alor-Pantar languages²",
                    116: u"Sprachliche Imitation",
                    154: u"Dynamische Modellierung von Artikulation und prosodischer Struktur",
                    163: u"A lexicalist account of argument structure",
                    195: u"Grammatical theory²",
                    255: u"Grammatical theory³",
                    210: u"Sound change, priming, salience",
                    197: u"Syntax with oscillators and energy levels",
                    186: u"Analogical classification in formal grammar",
                    233: u"Information-theoretic causal inference of  lexical flow",
                    250: u"A grammar of Sanzhi Dargwa",
                    278: u"Interpreting language-learning data",
                    283: u"Nominal anchoring",
                    252: u"Quantification and scales in change",
                    286: u"Historical journey in a linguistic archipelago",
                    280: u"Advances in formal Slavic linguistics 2018",
                    303: u"Computational approaches to semantic change",
                    277: u"Syntactic architecture and its consequences III",
                    312: u"Forthcoming: The Handbook of Lexical Functional Grammar",
                    288: u"Translation, interpreting, cognition",
                    304: u"Formulaic language",
                    311: u"Holisms of communication: The early history of audio-visual sequence analysis",
                    313: u"Individual differences in early instructed language learning",
                    178: u"Information structure in spoken Japanese",
                    251: u"Sound structure and sound change",
                    219: u"Information structure in Isthmus Zapotec narrative and conversation",
                    179: u"A tale of two dialect regions",
                    305: u"German(ic) in language contact",
                    281: u"Categoriality and continuity in prosodic prominence",
                    265: u"Utterance structure in initial L2 acquisition",
                    80:  u"Dual aspectual forms and event structure in Caribbean English Creoles",
                    256: u"The clausal syntax of German Sign Language",
                    213: u"Multi-verb constructions in Eastern Indonesia",
                    228: u"Metathesis and unmetathesis in Amarasi",
                    274: u"Language and scientific explanation",
                    248: u"Communication and content",
                    271: u"Voice at the interfaces",
                    230: u"Die Entwicklung des Definitartikels im Althochdeutschen",
                    194: u"Semantic differences in translation",
                    177: u"语法理论",
                    270: u"On a law of Indo-European word order",
                    299: u"OV and VO variation in code-switching",
                    298: u"A grammar of Gyeli",
                    262: u"One-to-many-relations in morphology, syntax, and semantics",
                    317: u"Subatomic quantification",
                    316: u"Formal approaches to number in Slavic and beyond",
                    308: u"A grammar of Tuatschin",
                    315: u"Voice syncretism",
                    150: u"Russian verbal prefixation",
                    142: u"Reflections on language evolution",
                    327: u"Phonology in the Twentieth Century",
                    326: u"A dictionary and grammatical sketch of Ruruuli-Lunyala",
                    332: u"Forthcoming: Contemporary research in minority and diaspora languages of Europe",
                    323: u"The size of things",
                    289: u"Explaining Russian-German code-mixing: A usage-based approach",
                    321: u"Experimental investigations on the syntax and usage of fragments",
                    236: u"Prácticas lingüísticas heterogéneas",
                    292: u"Forthcoming: Language change for the worse",
                    320: u"Emergent phonology",
                    318: u"Paradigms regained",
                    339: u"Clitics in the wild",
                    340: u"Informationsintegration in mehrsprachigen Textchats",
                    329: u"Morphosyntactic change in Late Modern Swedish",
                    341: u"The emergence of American English as a discursive variety",
                    }
