"""
Adapt an index generated by XeLaTeX so that it sorts words containing diacritics correctly

The ways how the *dx files are generated varies between different versions of TexLive
"""

import re, sys
from asciify import ASCIITRANS, REPLACEMENTS, is_ascii

# the LaTeX index entries consist of the string to be displayed (after the "@")
# and the string used for sorting (before the "@"). 
p = re.compile(r"\\indexentry \{(.*?)@")

   
def processline(s): 
  if s.strip() == '':
    return s  
  #find the substring used for sorting
  m = p.match(s) 
  sortstring = ''
  try:
    sortstring = m.groups(1)[0] 
  except AttributeError:
    print("%s could not be parsed" % repr(s))   
  #get rid of Latex diacritics like {\'{e}}   
  latexdiacritics = """'`^~"=.vdH"""
  tmpstring = re.sub(r"{\\[%s]{([A-Za-z])}}"%latexdiacritics,r"\1",sortstring)  
  #get rid of Latex diacritics like \'{e}
  tmpstring = re.sub(r"\\[%s]{([A-Za-z])}"%latexdiacritics,r"\1",tmpstring)    
  #get rid of Latex diacritics like \'e
  tmpstring = re.sub(r"\\[%s]([A-Za-z])"%latexdiacritics,r"\1",tmpstring)   
  #1:1 Unicode:ASCII translations
  tmpstring = tmpstring.translate(ASCIITRANS) 
  #1:2 Unicode:ASCII translations
  for r in REPLACEMENTS:
    tmpstring = tmpstring.replace(r[0],r[1])
  if sortstring == tmpstring:    
    return s
  else:
    print("%s => %s"%(sortstring,tmpstring))
    return s.replace("%s@"%sortstring,"%s@"%tmpstring) 
  
def processfile(filename): 
  print("Reading", filename)  
  with open(filename) as indexfile:
    lines = indexfile.readlines()
  print("Found %i lines" % len(lines))
  #read all lines, process them and write them to output file
  processedlines = list(map(processline, lines))
  with open(filename.replace('.','mod.'),'w') as out:
    out.write(''.join(processedlines))

if __name__ == '__main__':
  """
  Transform a file main._dx into mainmod._dx, where the underscore represents an index type given in the argument.

  Index types are:
  a: author index 
  s: subject index 
  l: language index

  Usage 
  > python3 fixindex.py 
  fixes the author index only. Read: main.adx. Write: mainmod.adx
  > python3 fixindex.py a
  fixes the author index only. Read: main.adx. Write: mainmod.adx
  > python3 fixindex.py l
  fixes the language index only. Read: main.ldx. Write: mainmod.ldx
  > python3 fixindex.py lsa
  fixes all three index types. Read: main.adx, main.ldx, main.sdx. Write: mainmod.adx, mainmod.ldx, mainmod.sdx
  """
  indextypes = 'a'  
  try:
      indextypes = sys.argv[1]
  except IndexError:
      pass
  for indextype in indextypes:
      processfile("main.%sdx" % indextype)
  
  